### PR TITLE
Loader fixes

### PR DESCRIPTION
**Pull request by geometer**
and please cherry-pick this change into 2.0.9 release

### CODE REVIEW

**Comment by ostolop** [comment]
@alf or @olkin -- could you review & merge, please?

**Comment by alf** [comment]
No, I can't since I'm not a part of this project. Please make sure you tag the correct person next time.  

## 

Alf Lervåg

**Comment by ostolop** [comment]
oops -- @alf239, @olgamelnichuk of course...

**Comment by ostolop** [comment]
This is for trac ticket #3053.

**Comment by olgamelnichuk** [comment]
Probably using another type of exception instead of false could be a bit better, but I don't insist

**Pull request merged**
