### PR TITLE
Trac3149

### PR DESCRIPTION
**Pull request by rpetry**
@olgamelnichuk, @alf239 - could you review please

### CODE REVIEW

**Comment by alf239** [comment]
We're likely to create a _huge_ conflict with the changes in #132; could we please postpone it until #132 is merged in?

**Comment by rpetry** [comment]
This pull request should be reviewed after https://github.com/gxa/gxa/pull/132 has been merged in.

**Comment by alf239** [comment]
This pull request cannot be automatically merged.

**Comment by rpetry** [comment]
Branch deprecated by trac3149b

**Pull request closed without merging**
