### PR TITLE
Wiggle fixes; sample <-> assay mapping

### PR DESCRIPTION
**Pull request by geometer**

### CODE REVIEW

**Comment by alf239** [comment]
I believe I've already merged at least haf of those changes (e.g. getting rid of `NetCDFReader`) — is it really the commits you had in mind?

**Comment by geometer** [comment]
You've merged wiggle fixes I think. This pull request is about sample <-> assay mappings.

**Comment by alf239** [comment]
Well, it cannot be merged automatically, so it's not as if I could be of much help. Also, the diff doesn't seem to agree with the declared goal of the fix.

Could you please make sure that the requests are mergeable and in line with their description?

**Comment by alf239** [comment]
Closing as obsolete — will be waiting for a new one

**Pull request closed without merging**
