### PR TITLE
Trac2973

### PR DESCRIPTION
**Pull request by rpetry**
Ticket #2973 - Added option to display efo terms instead of ef-efvs in Experiment API output.
@olgamelnichuk, @alf239 - could you review please

### CODE REVIEW

**Comment by olgamelnichuk** [comment]
Why not to show both ef/efv pair and efo term?

**Comment by olgamelnichuk** [comment]
I've added comments to the issue: http://bar.ebi.ac.uk:8080/trac/ticket/2973#comment:4

**Comment by rpetry** [comment]
Thanks Olga - I've added some comments in the ticket also.

**Comment by alf239** [comment]
Closing the pull request until [Trac 2973](http://bar.ebi.ac.uk:8080/trac/ticket/2973) is addressed

**Pull request closed without merging**
