### PR TITLE
Trac3006 Display EF for EFVs in autocomplete

### PR DESCRIPTION
**Pull request by olgamelnichuk**
Now showing all found efv in the autocomplete. Factor name added to the view of efv autocomplte item.

### CODE REVIEW

**Comment by alf239** [comment]
Seems fine; the only question is, we have `biopsy tissue` twice here — how come?

screencap

**Comment by olgamelnichuk** [comment]
There are two `biopsy tissue` : `liver`, one with a space at the end and another without space. To check this, go to the production database and run the following query:

``` sql
SELECT min(p.propertyid), p.name, min(pv.propertyvalueid), pv.name 
  FROM a2_property p, a2_propertyvalue pv 
 WHERE  pv.propertyid=p.propertyid AND p.name='biopsy tissue' 
 and pv.name like 'liver%' GROUP BY p.name, pv.name
```

**Comment by alf239** [comment]
@ostolop — the change itself is okay, are we okay with semi-duplicated EFVs?

**Comment by ostolop** [comment]
disease_state and organism_part should come from curatedEF

**Comment by olgamelnichuk** [comment]
Curated factor names should be shown now

**Comment by olgamelnichuk** [comment]
Earlier it was just a quick solution. Property is not exactly what we want to show here. The default view of autocomplete item doesn't require to show its property in gray color after its name. So I prefer to show exactly what is required. If there is no factorName then show nothing.

**Pull request merged**
